version: 3

tasks:
  test:
    desc: Build the ethgen binary and run tests
    cmds:
      - cd example && go run ethgen.go && cd .. && go test ./example/...

  test:coverage:
    desc: Run tests with coverage reporting
    cmds:
      - go test -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -html=coverage.out -o coverage.html
      - go tool cover -func=coverage.out

  test:coverage:check:
    desc: Run tests and check coverage thresholds
    cmds:
      - go test -coverprofile=coverage.out -covermode=atomic ./...
      - |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Total coverage: $COVERAGE%"

  clean:
    desc: Clean generated files
    cmds:
      - rm -f coverage.out coverage.html